# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.check_guest_additions = false
  end

  # Máquina ARQ (servidor de arquivos)
  config.vm.define "arq" do |arq|
    arq.vm.hostname = "arq.mihael.guilherme.devops"
    arq.vm.network "private_network", ip: "192.168.56.112"
    arq.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"

    arq.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end

  # Máquina DB (servidor de banco de dados)
  config.vm.define "db" do |db|
    db.vm.hostname = "db.mihael.guilherme.devops"
    db.vm.network "private_network", type: "dhcp"
    db.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end

  # Máquina APP (servidor de aplicação)
  config.vm.define "app" do |app|
    app.vm.hostname = "app.mihael.guilherme.devops"
    app.vm.network "private_network", type: "dhcp"
    app.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"

    app.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
  end

  # Máquina CLI (host cliente)
  config.vm.define "cli" do |cli|
    cli.vm.hostname = "cli.mihael.guilherme.devops"
    cli.vm.network "private_network", type: "dhcp"
    cli.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"

    cli.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
  end
end

